/**
 * va-api
 * va-api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Location, \'id\'>, schemaOptions: { title: \'NewLocation\', exclude: [ \'id\' ] })
 */
export interface NewLocation { 
    name: string;
    address: string;
    phone: string;
    lat: number;
    lng: number;
    url: string;
}

