/**
 * va-api
 * va-api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Vaccination, \'id\'>, schemaOptions: { title: \'NewVaccination\', exclude: [ \'id\' ] })
 */
export interface NewVaccination { 
    province?: string;
    population?: number;
    firstDoses?: number;
    secondDoses?: number;
    received?: number;
}

