/**
 * va-api
 * va-api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfile { 
    id?: string;
    province: string;
    age: number;
    homeCare?: boolean;
    healthCare?: boolean;
    frontline?: boolean;
    indigenous?: boolean;
    congregated?: boolean;
    essential?: boolean;
    pregnant?: boolean;
    email?: string;
}

