/**
 * va-api
 * va-api
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Vaccination { 
    id?: string;
    province?: string;
    population?: number;
    firstDoses?: number;
    secondDoses?: number;
    received?: number;
    phase1Date?: string;
    phase2Date?: string;
    phase3Date?: string;
}

